'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EO_ALANSIS_KIRAZ_MAMULDEPO
    Public Property ID As Integer
    Public Property TARIH As String
    Public Property STOK_KODU As String
    Public Property SERI As String
    Public Property MIKTAR As Nullable(Of Integer)
    Public Property BOLGE As String
    Public Property EBAT As String
    Public Property ISLEM As String
    Public Property KIRAZ_ISLEM As String
    Public Property ODA As String
    Public Property KALINTI As String
    Public Property DARA As Nullable(Of Integer)
    Public Property BRUT As Nullable(Of Integer)
    Public Property DEPO As String
    Public Property TIP As String
    Public Property PARTINO As String
    Public Property URETIM_TIPI As String
    Public Property CESIT As String
    Public Property USR As String
    Public Property ACIKLAMA As String
    Public Property RENK As String
    Public Property STOK_ISLEM As Nullable(Of Integer)
    Public Property AKTARILAN_URETICI As String
    Public Property AKTARILAN_KUTUSAYI As Nullable(Of Decimal)
    Public Property AKTARILAN_KG As Nullable(Of Decimal)
    Public Property SEVK_ONAY As String
    Public Property SEVK_MIKTAR As Nullable(Of Decimal)
    Public Property SEVKID As String
    Public Property EKALAN1 As String
    Public Property EKALAN2 As String
    Public Property EKALAN4 As String
    Public Property EKALAN5 As String
    Public Property EKALAN6 As Nullable(Of Decimal)
    Public Property EKALAN7 As Nullable(Of Decimal)
    Public Property EKALAN8 As Nullable(Of Decimal)
    Public Property EKALAN9 As Nullable(Of Decimal)
    Public Property EKALAN10 As Nullable(Of Decimal)
    Public Property EKALAN3 As String

End Class
