Public Class Form124
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_SEVKIYAT_TRANSITSURETableAdapter1.Fill(AlansısDataSet91.EO_ALANSIS_SEVKIYAT_TRANSITSURE)
    End Sub
End Class