Public Class Form243
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_SEVKIYATDENIZTableAdapter1.Fill(AlansısDataSet571.EO_ALANSIS_SEVKIYATDENIZ)
    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        Dim path As String = "DENIZYOLU_LOJISTIK_RAPOR.XLSX"
        PivotGridControl1.ExportToXlsx(path)
        ' Open the created XLSX file with the default application.
        Process.Start(path)
    End Sub
End Class