Public Class Form244
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_SEVKIYATHAVATableAdapter1.Fill(AlansısDataSet581.EO_ALANSIS_SEVKIYATHAVA)
    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        Dim path As String = "HAVAYOLU_LOJISTIK_RAPOR.XLSX"
        PivotGridControl1.ExportToXlsx(path)
        ' Open the created XLSX file with the default application.
        Process.Start(path)
    End Sub
End Class