Public Class Form166
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_HUCREBAKIYEMADTableAdapter1.Fill(AlansısDataSet221.EO_ALANSIS_HUCREBAKIYEMAD)
    End Sub

    Private Sub GridControl1_Click(sender As Object, e As EventArgs)

    End Sub

    Private Sub Form166_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: Bu kod satırı 'ALANSISDataSet33.EO_ALANSIS_HUCREBAKIYEMAD' tablosuna veri yükler. Bunu gerektiği şekilde taşıyabilir, veya kaldırabilirsiniz.
        Me.EO_ALANSIS_HUCREBAKIYEMADTableAdapter.Fill(Me.ALANSISDataSet33.EO_ALANSIS_HUCREBAKIYEMAD)

    End Sub

    Private Sub GridControl1_Click_1(sender As Object, e As EventArgs) Handles GridControl1.Click

    End Sub
End Class