Public Class Form179
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        'EO_ALANSIS_YUKLEMETAKIP_HAMMADDETableAdapter1.Fill(AlansısDataSet361.EO_ALANSIS_YUKLEMETAKIP_HAMMADDE)
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_YUKLEMETAKIP_HAMMADDETableAdapter2.Fill(AlansısDataSet381.EO_ALANSIS_YUKLEMETAKIP_HAMMADDE)
        ' This line of code is generated by Data Source Configuration Wizard

        ' This line of code is generated by Data Source Configuration Wizard

    End Sub
End Class