Public Class Form122
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_SEVKIYATYUKLEMEDURUMTableAdapter1.Fill(AlansısDataSet71.EO_ALANSIS_SEVKIYATYUKLEMEDURUM)
    End Sub
End Class