Public Class Form150
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_GGNPARTITableAdapter1.Fill(AlansısDataSet161.EO_ALANSIS_GGNPARTI)
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_GGNPARTITableAdapter2.Fill(AlansısDataSet162.EO_ALANSIS_GGNPARTI)
    End Sub

    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.Click

    End Sub
End Class