Public Class Form169
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_KALITEMADIZLEMETableAdapter.Fill(ALANSISDataSet23.EO_ALANSIS_KALITEMADIZLEME)
    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        Dim path As String = "output.xlsx"
        GridControl1.ExportToXlsx(path)
        ' Open the created XLSX file with the default application.
        Process.Start(path)
    End Sub

    Private Sub SimpleButton2_Click(sender As Object, e As EventArgs)

    End Sub

    Private Sub Form169_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: Bu kod satırı 'ALANSISDataSet23.EO_ALANSIS_KALITEMADIZLEME' tablosuna veri yükler. Bunu gerektiği şekilde taşıyabilir, veya kaldırabilirsiniz.
        Me.EO_ALANSIS_KALITEMADIZLEMETableAdapter.Fill(Me.ALANSISDataSet23.EO_ALANSIS_KALITEMADIZLEME)

    End Sub
End Class