Public Class Form123
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_SEVKIYAT_TESLIMFARKTableAdapter1.Fill(AlansısDataSet81.EO_ALANSIS_SEVKIYAT_TESLIMFARK)
    End Sub

    Private Sub Form123_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub
End Class