Imports System.Data.SqlClient
Imports DevExpress.Compatibility
Imports DevExpress.Data
Imports DevExpress.XtraGrid.Columns
Public Class Form138
    Dim SqlConnStr As String = "server=10.3.11.61;database=ALANSIS;uid=sa;pwd=term.0907;"
    Dim SqlConn As New System.Data.SqlClient.SqlConnection(SqlConnStr)
    Dim cmd As New SqlCommand()
    Dim cnn As New SqlConnection()
    Dim da As New SqlDataAdapter()
    Dim ds As New DataSet
    Sub New()
        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_HUCRESERI_BAKIYETableAdapter1.Fill(AlansısDataSet131.EO_ALANSIS_HUCRESERI_BAKIYE)
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_HUCRESERI_BAKIYETableAdapter2.Fill(AlansısDataSet132.EO_ALANSIS_HUCRESERI_BAKIYE)
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_HUCRESERI_BAKIYETableAdapter3.Fill(AlansısDataSet133.EO_ALANSIS_HUCRESERI_BAKIYE)
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_HUCRESERI_BAKIYETableAdapter4.Fill(AlansısDataSet134.EO_ALANSIS_HUCRESERI_BAKIYE)
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_HUCRESERI_BAKIYETableAdapter5.Fill(AlansısDataSet135.EO_ALANSIS_HUCRESERI_BAKIYE)
    End Sub
    Private Sub Form138_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: Bu kod satırı 'ALANSISDataSet13.EO_ALANSIS_HUCRESERI_BAKIYE' tablosuna veri yükler. Bunu gerektiği şekilde taşıyabilir, veya kaldırabilirsiniz.
        Me.EO_ALANSIS_HUCRESERI_BAKIYETableAdapter.Fill(Me.ALANSISDataSet13.EO_ALANSIS_HUCRESERI_BAKIYE)
        GridView1.OptionsSelection.MultiSelect = True
        GridView1.OptionsSelection.MultiSelectMode = DevExpress.XtraGrid.Views.Grid.GridMultiSelectMode.CheckBoxRowSelect
    End Sub
    Private Sub GridControl1_KeyDown(sender As Object, e As KeyEventArgs) Handles GridControl1.KeyDown
        ListBox1.Items.Clear()
        If (e.KeyCode = Keys.Tab) Then
            Dim toplam As Integer
            toplam = 0
            Dim ret As String = ""
            For Each i As Integer In GridView1.GetSelectedRows()
                Dim row As DataRow = GridView1.GetDataRow(i)
                If ret <> "" Then
                    ret &= ControlChars.CrLf
                End If
                toplam = toplam + Convert.ToInt16(row("SERI_BAKIYE"))
                '========================================================================================================
                ListBox1.Items.Add(row("SERI"))
            Next i
            TextEdit1.Text = toplam
        End If
    End Sub
    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        On Error GoTo hata
        Dim conn1 As New SqlConnection
        Dim cmd1 As New SqlCommand
        Dim cmd2 As New SqlCommand
        Dim da As New SqlDataAdapter()
        Dim ds As New DataSet
        Dim serilist, stokkodu, yerlesim, geldigi_yer, renk, serikontrol As String
        Dim seribakiye, listkontrol As Integer
        Dim partimiktar, listmiktar As Decimal
        serilist = ""
        serikontrol = ""
        stokkodu = ""
        yerlesim = ""
        geldigi_yer = ""
        renk = ""
        seribakiye = 0
        listkontrol = 0
        partimiktar = TextEdit4.Text
        listmiktar = Convert.ToInt16(TextEdit1.Text)
        If listmiktar > partimiktar Then
            DevExpress.XtraEditors.XtraMessageBox.Show("Seçim Miktarı, Parti Üretim Miktarından büyük olamaz...")
            Exit Sub
        End If
        listkontrol = ListBox1.Items.Count
        If listkontrol > 0 Then
            '------------------------------------------------------------------------------------------------------------------------------
            conn1.ConnectionString = "server=10.3.11.61;database=ALANSIS;uid=sa;pwd=term.0907"
            '-----------------------------------------------------------------------------------------
            For i As Integer = 0 To ListBox1.Items.Count - 1
                serilist = ListBox1.Items(i)
                '---------------------------------------------------------------------------------------------------------------
                conn1.Open()
                Dim mySelectQuery1 As String = "SELECT* FROM EO_ALANSIS_HAMMADDEONAY WHERE SERI='" & serilist & "' AND PARTINO='" & TextEdit2.Text & "';"
                Dim SqlComm1 As New System.Data.SqlClient.SqlCommand(mySelectQuery1, conn1)
                Dim reader1 As System.Data.SqlClient.SqlDataReader
                reader1 = SqlComm1.ExecuteReader()
                While reader1.Read()
                    serikontrol = reader1("SERI")
                End While
                reader1.Close()
                conn1.Close()
                If serikontrol = "" Then
                    '---------------------------------------------------------------------------------------------------------------
                    conn1.Open()
                    Dim mySelectQuery2 As String = "SELECT* FROM EO_ALANSIS_HAMHARSERI WHERE SERI='" & serilist & "';"
                    Dim SqlComm2 As New System.Data.SqlClient.SqlCommand(mySelectQuery2, conn1)
                    Dim reader2 As System.Data.SqlClient.SqlDataReader
                    reader2 = SqlComm2.ExecuteReader()
                    While reader2.Read()
                        stokkodu = reader2("STOK_KODU")
                        yerlesim = reader2("YERLESIM")
                        geldigi_yer = reader2("GELDIGI_YER")
                        renk = reader2("RENK")
                        seribakiye = Convert.ToInt16(reader2("MIKTAR"))
                    End While
                    reader2.Close()
                    conn1.Close()
                    '---------------------------------------------------------------------------------------------------------------
                    conn1.Open()
                    cmd1.Connection = conn1
                    cmd1.CommandText = "INSERT INTO EO_ALANSIS_HAMMADDEONAY (PARTINO,STOK_KODU,SERI,YERLESIM,GELDIGI_YER,RENK,SERI_BAKIYE,URETIM_ONAY) VALUES ( '" & TextEdit2.Text & "','" & stokkodu & "','" & serilist & "','" & yerlesim & "','" & geldigi_yer & "','" & renk & "','" & seribakiye & "','OK')"
                    cmd1.ExecuteNonQuery()
                    '--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                    conn1.Close()
                    '---------------------------------------------------------------------------------------------------
                End If
            Next
            TextEdit1.Text = ""
            TextEdit2.Text = ""
            TextEdit3.Text = ""
            TextEdit4.Text = ""
            DevExpress.XtraEditors.XtraMessageBox.Show("Kayıt İşlemi tamamlanmıştır...")
            Form131.ComboBoxEdit16.Text = "OK"

            Form131.Show()
            Me.Close()
            Exit Sub
        End If
        If listkontrol <= 0 Then
            DevExpress.XtraEditors.XtraMessageBox.Show("Lütfen seri seçim yapınız...")
            Exit Sub
        End If
hata:
        DevExpress.XtraEditors.XtraMessageBox.Show("Kayıt İşleminde hata, kontrol ediniz...")
        Exit Sub
    End Sub
    Private Sub GridControl1_Click(sender As Object, e As EventArgs) Handles GridControl1.Click
        On Error Resume Next
        Dim seri
        seri = GridView1.GetRowCellValue(GridView1.FocusedRowHandle, "SERI").ToString()
        DataGridView1.DataSource = ds
        ds.Clear()
        ds.Dispose()
        '=============================================================================================================================================================
        cnn.ConnectionString = "server=10.3.11.61;database=ALANSIS;uid=sa;pwd=term.0907"
        cnn.Open()
        cmd.Connection = cnn
        cmd.CommandType = CommandType.Text
        cmd.CommandText = "SELECT [PARTINO],[STOK_KODU],[SERI],[YERLESIM],[GELDIGI_YER],[RENK],[SERI_BAKIYE],[URETIM_ONAY],[MEYVE_ONAY],[ZIRAI_ONAY] FROM [dbo].[EO_ALANSIS_HAMMADDEONAY] WHERE SERI='" & seri & "'"
        da.SelectCommand = cmd
        DataGridView1.ClearSelection()
        da.Fill(ds)
        DataGridView1.DataSource = ds.Tables(0).DefaultView
        '=============================================================================================================================================================
        cnn.Close()
        DataGridView1.AutoResizeColumns(DataGridViewAutoSizeColumnMode.AllCells)
        For i = 0 To DataGridView1.Rows.Count - 1 Step 2
            DataGridView1.Rows(i).DefaultCellStyle.BackColor = Color.LemonChiffon
        Next
        '------------------------------------------------------------------------------
    End Sub
End Class