Public Class Form125
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_SEVKIYAT_NAKLIYETableAdapter1.Fill(AlansısDataSet101.EO_ALANSIS_SEVKIYAT_NAKLIYE)
    End Sub
End Class