Public Class Form120
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        EO_ALANSIS_SEVKIYATTableAdapter1.Fill(AlansısDataSet51.EO_ALANSIS_SEVKIYAT)
    End Sub
End Class