'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="ALANSIS")>  _
Partial Public Class DataClasses1DataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertEO_ALANSIS_KIRAZ_MAMULDEPO(instance As EO_ALANSIS_KIRAZ_MAMULDEPO)
    End Sub
  Partial Private Sub UpdateEO_ALANSIS_KIRAZ_MAMULDEPO(instance As EO_ALANSIS_KIRAZ_MAMULDEPO)
    End Sub
  Partial Private Sub DeleteEO_ALANSIS_KIRAZ_MAMULDEPO(instance As EO_ALANSIS_KIRAZ_MAMULDEPO)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.WindowsApplication1.My.MySettings.Default.ALANSISConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property EO_ALANSIS_KIRAZ_MAMULDEPO() As System.Data.Linq.Table(Of EO_ALANSIS_KIRAZ_MAMULDEPO)
		Get
			Return Me.GetTable(Of EO_ALANSIS_KIRAZ_MAMULDEPO)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.EO_ALANSIS_KIRAZ_MAMULDEPO")>  _
Partial Public Class EO_ALANSIS_KIRAZ_MAMULDEPO
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _TARIH As String
	
	Private _STOK_KODU As String
	
	Private _SERI As String
	
	Private _MIKTAR As System.Nullable(Of Integer)
	
	Private _BOLGE As String
	
	Private _EBAT As String
	
	Private _ISLEM As String
	
	Private _KIRAZ_ISLEM As String
	
	Private _ODA As String
	
	Private _KALINTI As String
	
	Private _DARA As System.Nullable(Of Integer)
	
	Private _BRUT As System.Nullable(Of Integer)
	
	Private _DEPO As String
	
	Private _TIP As String
	
	Private _PARTINO As String
	
	Private _URETIM_TIPI As String
	
	Private _CESIT As String
	
	Private _USR As String
	
	Private _ACIKLAMA As String
	
	Private _RENK As String
	
	Private _STOK_ISLEM As System.Nullable(Of Integer)
	
	Private _AKTARILAN_URETICI As String
	
	Private _AKTARILAN_KUTUSAYI As System.Nullable(Of Decimal)
	
	Private _AKTARILAN_KG As System.Nullable(Of Decimal)
	
	Private _SEVK_ONAY As String
	
	Private _SEVK_MIKTAR As System.Nullable(Of Decimal)
	
	Private _SEVKID As String
	
	Private _test As String
	
	Private _xxx As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnTARIHChanging(value As String)
    End Sub
    Partial Private Sub OnTARIHChanged()
    End Sub
    Partial Private Sub OnSTOK_KODUChanging(value As String)
    End Sub
    Partial Private Sub OnSTOK_KODUChanged()
    End Sub
    Partial Private Sub OnSERIChanging(value As String)
    End Sub
    Partial Private Sub OnSERIChanged()
    End Sub
    Partial Private Sub OnMIKTARChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnMIKTARChanged()
    End Sub
    Partial Private Sub OnBOLGEChanging(value As String)
    End Sub
    Partial Private Sub OnBOLGEChanged()
    End Sub
    Partial Private Sub OnEBATChanging(value As String)
    End Sub
    Partial Private Sub OnEBATChanged()
    End Sub
    Partial Private Sub OnISLEMChanging(value As String)
    End Sub
    Partial Private Sub OnISLEMChanged()
    End Sub
    Partial Private Sub OnKIRAZ_ISLEMChanging(value As String)
    End Sub
    Partial Private Sub OnKIRAZ_ISLEMChanged()
    End Sub
    Partial Private Sub OnODAChanging(value As String)
    End Sub
    Partial Private Sub OnODAChanged()
    End Sub
    Partial Private Sub OnKALINTIChanging(value As String)
    End Sub
    Partial Private Sub OnKALINTIChanged()
    End Sub
    Partial Private Sub OnDARAChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnDARAChanged()
    End Sub
    Partial Private Sub OnBRUTChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnBRUTChanged()
    End Sub
    Partial Private Sub OnDEPOChanging(value As String)
    End Sub
    Partial Private Sub OnDEPOChanged()
    End Sub
    Partial Private Sub OnTIPChanging(value As String)
    End Sub
    Partial Private Sub OnTIPChanged()
    End Sub
    Partial Private Sub OnPARTINOChanging(value As String)
    End Sub
    Partial Private Sub OnPARTINOChanged()
    End Sub
    Partial Private Sub OnURETIM_TIPIChanging(value As String)
    End Sub
    Partial Private Sub OnURETIM_TIPIChanged()
    End Sub
    Partial Private Sub OnCESITChanging(value As String)
    End Sub
    Partial Private Sub OnCESITChanged()
    End Sub
    Partial Private Sub OnUSRChanging(value As String)
    End Sub
    Partial Private Sub OnUSRChanged()
    End Sub
    Partial Private Sub OnACIKLAMAChanging(value As String)
    End Sub
    Partial Private Sub OnACIKLAMAChanged()
    End Sub
    Partial Private Sub OnRENKChanging(value As String)
    End Sub
    Partial Private Sub OnRENKChanged()
    End Sub
    Partial Private Sub OnSTOK_ISLEMChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSTOK_ISLEMChanged()
    End Sub
    Partial Private Sub OnAKTARILAN_URETICIChanging(value As String)
    End Sub
    Partial Private Sub OnAKTARILAN_URETICIChanged()
    End Sub
    Partial Private Sub OnAKTARILAN_KUTUSAYIChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnAKTARILAN_KUTUSAYIChanged()
    End Sub
    Partial Private Sub OnAKTARILAN_KGChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnAKTARILAN_KGChanged()
    End Sub
    Partial Private Sub OnSEVK_ONAYChanging(value As String)
    End Sub
    Partial Private Sub OnSEVK_ONAYChanged()
    End Sub
    Partial Private Sub OnSEVK_MIKTARChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnSEVK_MIKTARChanged()
    End Sub
    Partial Private Sub OnSEVKIDChanging(value As String)
    End Sub
    Partial Private Sub OnSEVKIDChanged()
    End Sub
    Partial Private Sub OntestChanging(value As String)
    End Sub
    Partial Private Sub OntestChanged()
    End Sub
    Partial Private Sub OnxxxChanging(value As String)
    End Sub
    Partial Private Sub OnxxxChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TARIH", DbType:="NVarChar(MAX)")>  _
	Public Property TARIH() As String
		Get
			Return Me._TARIH
		End Get
		Set
			If (String.Equals(Me._TARIH, value) = false) Then
				Me.OnTARIHChanging(value)
				Me.SendPropertyChanging
				Me._TARIH = value
				Me.SendPropertyChanged("TARIH")
				Me.OnTARIHChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STOK_KODU", DbType:="NVarChar(MAX)")>  _
	Public Property STOK_KODU() As String
		Get
			Return Me._STOK_KODU
		End Get
		Set
			If (String.Equals(Me._STOK_KODU, value) = false) Then
				Me.OnSTOK_KODUChanging(value)
				Me.SendPropertyChanging
				Me._STOK_KODU = value
				Me.SendPropertyChanged("STOK_KODU")
				Me.OnSTOK_KODUChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SERI", DbType:="NVarChar(MAX)")>  _
	Public Property SERI() As String
		Get
			Return Me._SERI
		End Get
		Set
			If (String.Equals(Me._SERI, value) = false) Then
				Me.OnSERIChanging(value)
				Me.SendPropertyChanging
				Me._SERI = value
				Me.SendPropertyChanged("SERI")
				Me.OnSERIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MIKTAR", DbType:="Int")>  _
	Public Property MIKTAR() As System.Nullable(Of Integer)
		Get
			Return Me._MIKTAR
		End Get
		Set
			If (Me._MIKTAR.Equals(value) = false) Then
				Me.OnMIKTARChanging(value)
				Me.SendPropertyChanging
				Me._MIKTAR = value
				Me.SendPropertyChanged("MIKTAR")
				Me.OnMIKTARChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BOLGE", DbType:="NVarChar(MAX)")>  _
	Public Property BOLGE() As String
		Get
			Return Me._BOLGE
		End Get
		Set
			If (String.Equals(Me._BOLGE, value) = false) Then
				Me.OnBOLGEChanging(value)
				Me.SendPropertyChanging
				Me._BOLGE = value
				Me.SendPropertyChanged("BOLGE")
				Me.OnBOLGEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EBAT", DbType:="NVarChar(MAX)")>  _
	Public Property EBAT() As String
		Get
			Return Me._EBAT
		End Get
		Set
			If (String.Equals(Me._EBAT, value) = false) Then
				Me.OnEBATChanging(value)
				Me.SendPropertyChanging
				Me._EBAT = value
				Me.SendPropertyChanged("EBAT")
				Me.OnEBATChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISLEM", DbType:="NVarChar(MAX)")>  _
	Public Property ISLEM() As String
		Get
			Return Me._ISLEM
		End Get
		Set
			If (String.Equals(Me._ISLEM, value) = false) Then
				Me.OnISLEMChanging(value)
				Me.SendPropertyChanging
				Me._ISLEM = value
				Me.SendPropertyChanged("ISLEM")
				Me.OnISLEMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KIRAZ_ISLEM", DbType:="NVarChar(MAX)")>  _
	Public Property KIRAZ_ISLEM() As String
		Get
			Return Me._KIRAZ_ISLEM
		End Get
		Set
			If (String.Equals(Me._KIRAZ_ISLEM, value) = false) Then
				Me.OnKIRAZ_ISLEMChanging(value)
				Me.SendPropertyChanging
				Me._KIRAZ_ISLEM = value
				Me.SendPropertyChanged("KIRAZ_ISLEM")
				Me.OnKIRAZ_ISLEMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ODA", DbType:="NVarChar(MAX)")>  _
	Public Property ODA() As String
		Get
			Return Me._ODA
		End Get
		Set
			If (String.Equals(Me._ODA, value) = false) Then
				Me.OnODAChanging(value)
				Me.SendPropertyChanging
				Me._ODA = value
				Me.SendPropertyChanged("ODA")
				Me.OnODAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_KALINTI", DbType:="NVarChar(MAX)")>  _
	Public Property KALINTI() As String
		Get
			Return Me._KALINTI
		End Get
		Set
			If (String.Equals(Me._KALINTI, value) = false) Then
				Me.OnKALINTIChanging(value)
				Me.SendPropertyChanging
				Me._KALINTI = value
				Me.SendPropertyChanged("KALINTI")
				Me.OnKALINTIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DARA", DbType:="Int")>  _
	Public Property DARA() As System.Nullable(Of Integer)
		Get
			Return Me._DARA
		End Get
		Set
			If (Me._DARA.Equals(value) = false) Then
				Me.OnDARAChanging(value)
				Me.SendPropertyChanging
				Me._DARA = value
				Me.SendPropertyChanged("DARA")
				Me.OnDARAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BRUT", DbType:="Int")>  _
	Public Property BRUT() As System.Nullable(Of Integer)
		Get
			Return Me._BRUT
		End Get
		Set
			If (Me._BRUT.Equals(value) = false) Then
				Me.OnBRUTChanging(value)
				Me.SendPropertyChanging
				Me._BRUT = value
				Me.SendPropertyChanged("BRUT")
				Me.OnBRUTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DEPO", DbType:="NVarChar(50)")>  _
	Public Property DEPO() As String
		Get
			Return Me._DEPO
		End Get
		Set
			If (String.Equals(Me._DEPO, value) = false) Then
				Me.OnDEPOChanging(value)
				Me.SendPropertyChanging
				Me._DEPO = value
				Me.SendPropertyChanged("DEPO")
				Me.OnDEPOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TIP", DbType:="NVarChar(MAX)")>  _
	Public Property TIP() As String
		Get
			Return Me._TIP
		End Get
		Set
			If (String.Equals(Me._TIP, value) = false) Then
				Me.OnTIPChanging(value)
				Me.SendPropertyChanging
				Me._TIP = value
				Me.SendPropertyChanged("TIP")
				Me.OnTIPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PARTINO", DbType:="NVarChar(MAX)")>  _
	Public Property PARTINO() As String
		Get
			Return Me._PARTINO
		End Get
		Set
			If (String.Equals(Me._PARTINO, value) = false) Then
				Me.OnPARTINOChanging(value)
				Me.SendPropertyChanging
				Me._PARTINO = value
				Me.SendPropertyChanged("PARTINO")
				Me.OnPARTINOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_URETIM_TIPI", DbType:="NVarChar(MAX)")>  _
	Public Property URETIM_TIPI() As String
		Get
			Return Me._URETIM_TIPI
		End Get
		Set
			If (String.Equals(Me._URETIM_TIPI, value) = false) Then
				Me.OnURETIM_TIPIChanging(value)
				Me.SendPropertyChanging
				Me._URETIM_TIPI = value
				Me.SendPropertyChanged("URETIM_TIPI")
				Me.OnURETIM_TIPIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CESIT", DbType:="NVarChar(MAX)")>  _
	Public Property CESIT() As String
		Get
			Return Me._CESIT
		End Get
		Set
			If (String.Equals(Me._CESIT, value) = false) Then
				Me.OnCESITChanging(value)
				Me.SendPropertyChanging
				Me._CESIT = value
				Me.SendPropertyChanged("CESIT")
				Me.OnCESITChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_USR", DbType:="NVarChar(MAX)")>  _
	Public Property USR() As String
		Get
			Return Me._USR
		End Get
		Set
			If (String.Equals(Me._USR, value) = false) Then
				Me.OnUSRChanging(value)
				Me.SendPropertyChanging
				Me._USR = value
				Me.SendPropertyChanged("USR")
				Me.OnUSRChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACIKLAMA", DbType:="NVarChar(MAX)")>  _
	Public Property ACIKLAMA() As String
		Get
			Return Me._ACIKLAMA
		End Get
		Set
			If (String.Equals(Me._ACIKLAMA, value) = false) Then
				Me.OnACIKLAMAChanging(value)
				Me.SendPropertyChanging
				Me._ACIKLAMA = value
				Me.SendPropertyChanged("ACIKLAMA")
				Me.OnACIKLAMAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RENK", DbType:="NVarChar(50)")>  _
	Public Property RENK() As String
		Get
			Return Me._RENK
		End Get
		Set
			If (String.Equals(Me._RENK, value) = false) Then
				Me.OnRENKChanging(value)
				Me.SendPropertyChanging
				Me._RENK = value
				Me.SendPropertyChanged("RENK")
				Me.OnRENKChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STOK_ISLEM", DbType:="Int")>  _
	Public Property STOK_ISLEM() As System.Nullable(Of Integer)
		Get
			Return Me._STOK_ISLEM
		End Get
		Set
			If (Me._STOK_ISLEM.Equals(value) = false) Then
				Me.OnSTOK_ISLEMChanging(value)
				Me.SendPropertyChanging
				Me._STOK_ISLEM = value
				Me.SendPropertyChanged("STOK_ISLEM")
				Me.OnSTOK_ISLEMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AKTARILAN_URETICI", DbType:="NVarChar(MAX)")>  _
	Public Property AKTARILAN_URETICI() As String
		Get
			Return Me._AKTARILAN_URETICI
		End Get
		Set
			If (String.Equals(Me._AKTARILAN_URETICI, value) = false) Then
				Me.OnAKTARILAN_URETICIChanging(value)
				Me.SendPropertyChanging
				Me._AKTARILAN_URETICI = value
				Me.SendPropertyChanged("AKTARILAN_URETICI")
				Me.OnAKTARILAN_URETICIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AKTARILAN_KUTUSAYI", DbType:="Decimal(18,2)")>  _
	Public Property AKTARILAN_KUTUSAYI() As System.Nullable(Of Decimal)
		Get
			Return Me._AKTARILAN_KUTUSAYI
		End Get
		Set
			If (Me._AKTARILAN_KUTUSAYI.Equals(value) = false) Then
				Me.OnAKTARILAN_KUTUSAYIChanging(value)
				Me.SendPropertyChanging
				Me._AKTARILAN_KUTUSAYI = value
				Me.SendPropertyChanged("AKTARILAN_KUTUSAYI")
				Me.OnAKTARILAN_KUTUSAYIChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AKTARILAN_KG", DbType:="Decimal(18,2)")>  _
	Public Property AKTARILAN_KG() As System.Nullable(Of Decimal)
		Get
			Return Me._AKTARILAN_KG
		End Get
		Set
			If (Me._AKTARILAN_KG.Equals(value) = false) Then
				Me.OnAKTARILAN_KGChanging(value)
				Me.SendPropertyChanging
				Me._AKTARILAN_KG = value
				Me.SendPropertyChanged("AKTARILAN_KG")
				Me.OnAKTARILAN_KGChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SEVK_ONAY", DbType:="NVarChar(50)")>  _
	Public Property SEVK_ONAY() As String
		Get
			Return Me._SEVK_ONAY
		End Get
		Set
			If (String.Equals(Me._SEVK_ONAY, value) = false) Then
				Me.OnSEVK_ONAYChanging(value)
				Me.SendPropertyChanging
				Me._SEVK_ONAY = value
				Me.SendPropertyChanged("SEVK_ONAY")
				Me.OnSEVK_ONAYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SEVK_MIKTAR", DbType:="Decimal(18,2)")>  _
	Public Property SEVK_MIKTAR() As System.Nullable(Of Decimal)
		Get
			Return Me._SEVK_MIKTAR
		End Get
		Set
			If (Me._SEVK_MIKTAR.Equals(value) = false) Then
				Me.OnSEVK_MIKTARChanging(value)
				Me.SendPropertyChanging
				Me._SEVK_MIKTAR = value
				Me.SendPropertyChanged("SEVK_MIKTAR")
				Me.OnSEVK_MIKTARChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SEVKID", DbType:="NVarChar(MAX)")>  _
	Public Property SEVKID() As String
		Get
			Return Me._SEVKID
		End Get
		Set
			If (String.Equals(Me._SEVKID, value) = false) Then
				Me.OnSEVKIDChanging(value)
				Me.SendPropertyChanging
				Me._SEVKID = value
				Me.SendPropertyChanged("SEVKID")
				Me.OnSEVKIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_test", DbType:="NVarChar(MAX)")>  _
	Public Property test() As String
		Get
			Return Me._test
		End Get
		Set
			If (String.Equals(Me._test, value) = false) Then
				Me.OntestChanging(value)
				Me.SendPropertyChanging
				Me._test = value
				Me.SendPropertyChanged("test")
				Me.OntestChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_xxx", DbType:="NChar(10)")>  _
	Public Property xxx() As String
		Get
			Return Me._xxx
		End Get
		Set
			If (String.Equals(Me._xxx, value) = false) Then
				Me.OnxxxChanging(value)
				Me.SendPropertyChanging
				Me._xxx = value
				Me.SendPropertyChanged("xxx")
				Me.OnxxxChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
